#!/bin/bash
# plays a full scale for each 4 motors in polyphonic mode

source ./lib_send_midi.sh  # contains functions for sending MIDI events


lib_send_midi_play_scale_5
sleep 2
lib_send_midi_terminal_beep

lib_send_midi_activate_1_motor
sleep 2
lib_send_midi_terminal_beep
lib_send_midi_play_scale_5
sleep 2
lib_send_midi_terminal_beep
lib_send_midi_deactivate_1_motor

lib_send_midi_activate_2_motor
sleep 2
lib_send_midi_terminal_beep
lib_send_midi_play_scale_5
sleep 2
lib_send_midi_terminal_beep
lib_send_midi_deactivate_2_motor

lib_send_midi_activate_3_motor
sleep 2
lib_send_midi_terminal_beep
lib_send_midi_play_scale_5
sleep 2
lib_send_midi_terminal_beep
lib_send_midi_deactivate_3_motor

